### ISSUE TITLE
add intext citations

### ISSUE THREAD

**Issue by maxheld83** [soztag/crowd#24]
This is about the citations in `crowd_de.Rmd`.

The in-text citations currently all just text, and they need to be changed into the [respective pandoc markdown citation syntax](https://pandoc.org/MANUAL.html#citations).

For an example of the necessary changes, see 
https://github.com/soztag/crowd/commit/3413f975bfbb55f4d68ed12e379acf643e1a4ca3.

The necessary bibliographic entries *should* already all be in the `library.bib` file at the repository root.
This file has been exported from Sandras Zotero group.

If there are any missing, or necessary changes, please also change the entry in the Zotero group, and then re-export the Zotero group contents to `library.bib`. (You need the better bibtex plugin to Zotero installed for this to work well).

It'd be great if you could do this in a separate branch, which I can then merge once you're done.

Hope this is making sense.

**Comment by samshaffer97** [comment]
i've updated the citations for the entries that are currently in `library.bib` 
all others i have simply put in square brackets
i will update the other citations once i have access to the zotero group

**Comment by maxheld83** [comment]
thanks @samshaffer97 great work!
I'm now going to merge this into `master`.

**Comment by maxheld83** [comment]
good idea about putting the un-resolved citations simply in square brackets! Makes it easy to find them!

**Comment by maxheld83** [comment]
I'm going to try and fix the remaining ones myself, and/or alert Sandra to any missing literature.

**Comment by maxheld83** [comment]
@Sandra missing citations are:

- [ ] `Gläser/Laudel 2010`
- [ ] korrekte Angabe muss noch geprüft werden (Projekt Lanceo)
